### ISSUE TITLE
App crashes -  android.system.UnixSocketAddress cannot be cast to java.net.InetSocketAddress

### ISSUE THREAD

**Issue by fagnerrs** [NAXAM/mapbox-android-binding#18]
Hello,

I have been facing a crash using Mapbox version 5.5.2 and according what I've researched so far, the issue is caused by the Okhttp3 library, which Mapbox dependents on. The issue seems to be fixed on Okhttp3 library for java, but not on the Xamarin Binding (Square.OkHttp3).

Does anyone faced this problem before and know how to fix it or at least have a suggestion?
Thanks

Complete error:
Java.Lang.ClassCastException: android.system.UnixSocketAddress cannot be cast to java.net.InetSocketAddress
  at java.lang.ClassCastException: android.system.UnixSocketAddress cannot be cast to java.net.InetSocketAddress
  at at libcore.io.IoBridge.getLocalInetSocketAddress(IoBridge.java:700)
  at at libcore.io.IoBridge.connectDetail(IoBridge.java:197)
  at at libcore.io.IoBridge.connect(IoBridge.java:138)
  at at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
  at at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
  at at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
  at at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
  at at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
  at at java.net.Socket.connect(Socket.java:616)
  at at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:63)
  at at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:223)
  at at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
  at at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
  at at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
  at at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
  at at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
  at at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
  at at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  at at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
  at at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
  at at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
  at at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
  at at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
  at at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
  at at java.lang.Thread.run(Thread.java:764)

**Comment by tuyen-vuduc** [comment]
Have you tried latest version v6.4? You might try latest OkHttp3 version from our custom feed [here](https://www.myget.org/feed/naxam/package/nuget/Square.OkHttp3).

Cheers.

**Comment by fagnerrs** [comment]
Hi there,
I updated to the latest OkHttp3 version and it fixed the issue. Thank you!!
